### ISSUE TITLE
Non-exist endpoints returns 403 HTTP error instead of 404 

### ISSUE THREAD

**Issue by bwqr** [bounswe/bounswe2019group6#101]
For example when you try to reach endpoint `/hello`, the received response status is 403.

Is this behavior expected or a bug? Should not it return 404 response when requested endpoint does not exist?.

**Comment by enozcan** [comment]
Hi @bwqr,

If you make a request to a non-existing endpoint with token it will return 404.

That is actually an expected behavior since I've implemented it this way. Otherwise, ANYONE can decide if an endpoint exists or not in the system.

**Comment by bwqr** [comment]
That makes sense, however, since this project is open source, anyone can find out the endpoints easily.  To make it standard, even without a token, response should be 404. Otherwise we will be in trouble about sorting out what problem we are facing at the application side. 403 response can be confusing.

**Comment by barisegesevgili** [comment]
You are right about the point that project is open source, anyone can find out the endpoints easily. However, we should keep our structure secure without considering our project's being an open source project, since we can make it closed-source later on. And, on the other hand, while tracking what problem we are facing at the app. side we as developers have the information about which endpoints we have, thus It won't be a down-side. So, as backend team our decision is to keep it as it is for now. In case of further viewpoints to the issue emerges, pls do not hesitate update us and share your concerns.

**Comment by burakikanyildiz** [comment]
As my teammates said, we have developed our endpoints working underneath of a filter and since any non-authenticated user cannot pass the filter, we are returning 403 response. After long discussing, we have decided to implement this way by reason of security issues. Surely, we are open to consider any suggestions, concerns and changes. If you have more suggestions and concerns, please tell us. 
Therefore, if we don't have more concerns, we can close the issue.

**Comment by enozcan** [comment]
Closing the issue.
May be reopened after the weekly meet up discussion.
