### ISSUE TITLE
JWT storage location

### ISSUE THREAD

**Issue by bwqr** [bounswe/bounswe2019group6#102]
Hi android team!

After signin operation of a user, we receive a token from backend for other requests to authorize the user. Question is where we should store this token for the sake of persistency. We have a couple of options. We can store token in:
1. RoomDatabase
2. SharedPreferences
3. Or use Account Manager for the authentication.

For the security, first and second options should not be selected, however, third option is a little bit cumbersome to implement. What are your opinions about this challenge? Do you have any other options to store the token?

**Comment by mstfalp** [comment]
Database option is not really feasible for securing any content so we should eliminate that. 

SharedPreferences used quite a lot for single tokens (not passwords) since Android keeps application data separately and other apps can not access to that data directly. Only way would be using a rooted device and giving read permission to exact application folder. 

Account Manager is a general tool for handling many authentication related tasks but mostly used background sync operations which requires a service to up all the time. 

Also Keystore is widely used for this purpose https://developer.android.com/training/articles/keystore but I haven't tested or used it before. 

I feel like it would be better starting with a simpler solution for now and maybe update later if necessary. Therefore we can token in SharedPreference at start and switch to Keystore later if we want to.

**Comment by bwqr** [comment]
I also prefer to use SharedPreferences to store the token. As far as I know KeyStore is not the locatio of data storage, it is being used as private key storage for signing the data. That issue is concluded as JWT storage location is SharedPreferences
