### ISSUE TITLE
Error during signin, checking raw password with hashed password

### ISSUE THREAD

**Issue by burakikanyildiz** [bounswe/bounswe2019group6#119]
Even though password stored hashed in the database as expected, in login controller it checks the password parameter that user post with hashed password in the database. Therefore, no one can signin the system.

**Comment by enozcan** [comment]
Actually, the issue is not related to checking of hashed or non hashed password. Since our password policy says that it must contain at least one special character and since those special characters have to be sent in encoded form (due to URL encoding standards), when they are sent as request parameter the following scenario happens:

When one tries to send that request:
> BASE_URL:8080/login?username=usr1&password=Pass123#

It will be sent with ignoring the last # character. Instead, the '#' char must be replaced with its corresponding encoded value which is `'%23'`. (See more about URL encoding [here](https://www.w3schools.com/tags/ref_urlencode.asp))

As a solution,  we can change the way of sending that credentials from request parameters to body parameters. I've made a PR. Can you please review it or comment if you have another solution?

**Comment by burakikanyildiz** [comment]
As I have just reviewed and merged @enozcan PR. This issue is now resolved. So we can close the issue.
