### ISSUE TITLE
Endpoint request

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#164]
Now I am implementing edit profile page, however currently we don't have endpoints for updating `username`, `password` and `iban`. Can you add these endpoints?

**Comment by barisegesevgili** [comment]
Sure! We will plan it and update you again after the end of the back-end team meeting tomorrow.

**Comment by enozcan** [comment]
- To change password, use `password/change`
- IBAN and coordinates now can be edited via `user/edit` endpoint on 80d64a4. (active on backend-dev branch, not deployed yet)
- Since access tokens are created based on usernames, changing username will require extra amount of work and further will invalidate all the tokens created for that user. Hence, let's leave it not editable for now and discuss that feature if it's a must.

Closing the issue and another issue can be opened in particular for the username edit property.
