### ISSUE TITLE
Deciding "Trading Equipments" Endpoints

### ISSUE THREAD

**Issue by bwqr** [bounswe/bounswe2019group6#180]
Hi fellows,

Observing the previous endpoints changes, I think we should discuss about how endpoints should be defined and the what data they should include in themselves. First of all, I request to Backend team about their opinion about these two points which should be considered according to Project Requirements.

In that way, we can make more solid progress than going back and forth on endpoints changes. Obviously, there will be some changes after decision about the endpoints, however, should be less than previously.

**Comment by enozcan** [comment]
Hi @bwqr 
The last changes were an extreme case and we guarantee you there will be no such a situation again. Regarding to the other case you pointed out, I think it's not that possible to make an abstraction for the endpoint structure since they differ according to their functionality. However, any advice or request concerning the parameter types, structure etc. is appreciated.
