### ISSUE TITLE
My investments endpoint

### ISSUE THREAD

**Issue by sadullahgultekin** [bounswe/bounswe2019group6#218]
Hi @burakikanyildiz,
In "My Investments" page, I want to show all assets of a user has. But there isn't a proper endpoint for this functionality. Current version of the page is sending request for each trading equipment separately which is not so elegant. Can you write an endpoint like `asset/all` so that I can use.
Current response is in the form:
```
{ "amount":100.0 }
```
Something like the following would do the job:
```
{ "USD" : 100, "BTC" : 10, "JPY" : 20, "AMZN" : 400 }
```
Thank you in advance!

**Comment by burakikanyildiz** [comment]
Hello @sadullahgultekin , I have implemented the asset/all endpoint. However, because asset/{code} and asset/all may cause confusion. I have modified asset/{code} endpoint as asset/code/{code}.

* asset/all endpoint return example: 
```json
[
    {
        "user": "admin",
        "code": "USD",
        "amount": 18852.6
    },
    {
        "user": "admin",
        "code": "TRY",
        "amount": 200.0
    }
]
```

* asset/code/{code} endpoint return example (in this case code : USD):
```json
{
    "user": "admin",
    "code": "USD",
    "amount": 18852.6
}
```

**Comment by sadullahgultekin** [comment]
Thank you!
