### ISSUE TITLE
Edit user requirements according to feedback

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#26]
Until 02/03/2019 23:59

**Comment by burakikanyildiz** [comment]
-Functional requirements are updated, need to be reviewed.
-Non-functional requirements need to be updated @bwqr

**Comment by bwqr** [comment]
I have updated non-functional part of the requirements. You can review that part @burakikanyildiz . Can you check the items which are labeled with  //CHECK IT. I will check the functional requirements.

**Comment by bwqr** [comment]
Should we open new section about articles and commenting under user requirements? If we open this, we can add "annotating images and texts" inside this section. 

Since our system involves IBAN, we should add money transaction inside the system requirements.

As a new requirements, getting feedback from user should be discussed by group members.

**Comment by burakikanyildiz** [comment]
We have already mentioned about articles and commenting in trading equipment system under user requirements. If necessary, it can be modified.
I will add money transaction section.

**Comment by burakikanyildiz** [comment]
Monet transaction section is added.
