### ISSUE TITLE
[Backend] Status of follow requests on profile privacy change

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#272]
Currently, when a profile goes to public from private, the follow requests previously made for this profile remain as request. 

IMO all of them must be count as `accepted`. WDYT @barisegesevgili @burakikanyildiz ? If this is also OK for you, I will modify it accordingly.

**Comment by burakikanyildiz** [comment]
Hello @enozcan , actually there are two prominent approaches to this issue. 

1. **The Instagram Method:** Setting a profile to public is essentially "accepting all followers", so the pending requests just get marked as accepted. Reverting the profile back to private doesn't undo this action.

 2. **The Twitter Method:** Setting a profile to public allows everyone to follow, but setting it back to private restores the pending requests as they were before. This means that a follower that wasn't explicitly approved (i.e. one who had sent a request, but didn't get a response) will be back to waiting for approval.

Both behaviors look fine to me. However, from an UX perspective, normally users hate not being in control, especially when systems performs things automatically without approval. 

When switching to PUBLIC, we can hold in a separate list the requests received when the account was Private. And only accept the them when:

1. Account owner accepts the request (much like when they were in Private mode)
2. Follower cancels request and requests again. In this case, the follow request will be accepted instantly since it is being processed in PUBLIC mode.

If we decide to follow the Instagram Method, we should make sure to at least ask the user if they want to approve all the requests when switching to PUBLIC. Otherwise, we may automatically flood their account with hundreds of new followers. We should give them opportunity to reject the pending requests.

**Comment by barisegesevgili** [comment]
As @burakikanyildiz stated, a user always want everything to be under control and hates unexpected (non explicitly stated) behaviours of the system. Thus, my suggestion is to inform the user about system's behaviour as: 
*  "All of the follow request directed to you will be accepted in case switching your profile from private to public, do you confirm?"

After the confirmation, we can make the pending requests accepted.
If you also agree on that, we can finalize it in this way.

What do you think @enozcan @burakikanyildiz ?

**Comment by enozcan** [comment]
Good point @barisegesevgili. However such a feature also concerns frontend & android teams. We better ask them about that.

WDYT @msdalp @sadullahgultekin, is it OK for you to show a pop up or something before changing profile from private to public? Any other advice is appreciated.

**Comment by mstfalp** [comment]
Accepting all follow requests while switching privacy to public looks fine to me. There should be no need for additional service calls but only a visual warning on Android and Frontend. 
We can just add the warning and you can accept remaining requests on the backend. 
Additionally we can make it optional parameter with default like `profile/public?follows=true` or  `follows=false` with the default `follows=true`. 
![image](https://user-images.githubusercontent.com/43815119/71165582-27514b80-2262-11ea-95dc-c4ce6ccb7be5.png)

This way you don't need to wait for us to finish all features before deploying.

**Comment by enozcan** [comment]
Hi @mstfalp @sadullahgultekin,
We as backend team have talked again and decided on the acceptance of requests on such a situation. So, you now might show a pop up on changes from private to public as @mstfalp pointed out but without `decline` option.
