### ISSUE TITLE
Create & Design class diagram of the project

### ISSUE THREAD

**Issue by enozcan** [bounswe/bounswe2019group6#35]
Deadline 11.03.2019 @23:59

**Comment by barandenizkorkmaz** [comment]
The tasks assigned during the first meeting is as follows:
Deniz: User & Authorization Manager
Fatih: Event & Location & Tag & Comment % Annotation
Irmak and Burak, you should share the following assignments:
* Trading Equipment class & features
* Recommendation-Search Engine class & features

**Comment by barandenizkorkmaz** [comment]
I am going to be designing the classes Portfolio, ProfitLoss, and MyInvestments as well since they are related to the user class. However if there were any conflicts, we might discuss at the meeting tomorrow.

**Comment by barandenizkorkmaz** [comment]
Finally, i suggest that we can read the assignment pdf paragraph by paragraph and discuss if the features specified are currently included on our design and if they are under the true class definition. I am commenting just to notify every participant and to use as a remainder for us.

**Comment by barandenizkorkmaz** [comment]
If you're agree with the suggestion above, please comment. Otherwise, please suggest your own opinion, since tomorrow is the last day of the deadline we should increase the productivity as much as we can.

**Comment by burakyuksel0** [comment]
I arranged Articles and Trading Equipment classes on the Google doc. Please review and share your opinions.

**Comment by bwqr** [comment]
@burakyuksel0 I reviewed your arranged classes. As you have done in the Article class, you should change 'addTag' to 'addTags' since you are getting a list parameter. By the way, I have stated the Location, Tag, Comment and Event classes. Reviews will be appreciated.

**Comment by burakyuksel0** [comment]
@bwqr Thank you for correction. I reviewed your work. Here are my remarks: 
* In _Comment_ class, you used type _String_ for _created_at_ and _updated_at_ fields. I think we can assume there is a type _Date_, which I used in _Article_ class for _created_at_ field, or alternatively we can define a new class for _Date_ type.
* In _Location_ class, you shortened the field names as _lng_ and _lat_. I think the original versions are not too long and you can use them because I could not understand them at first and had to look them up. :)
* In _Location_ class, you used _fp32_ for floating point numbers. I used _Double_ instead. We should decide on which one to use to prevent confusion.

**Comment by bwqr** [comment]
@burakyuksel0 my bad, it's a typo. I corrected _created_at_ and _updated_at_ fields as Date. And you are right about location class. I changed the related fields as you stated. Thanks for your review.

**Comment by irmakguzey** [comment]
Hi everyone, I have updated Recommendation_Engine and Search_Engine classes. Any review will be much appreciated and is highly encouraged. 
And since both of the engines are using tags in order to search, I kindly request to people who are responsible of Article, Event, User, Location, Equipment classes to add a method such as _doesExist(tag:Tag)_. 
Thanks in advance!

**Comment by barandenizkorkmaz** [comment]
Bonjour mes amis. Thanks everyone for last updates. I just added my part into the doc. To avoid any conflicts, for now, the classes are under my name. Since we are going to make necessary regulations, there's no problem doing this way i think. Plus, my special thanks for increasing collaboration. Really nice teamwork going on. Let's make group 6 awesome! 😄

**Comment by irmakguzey** [comment]
Hi everyone, 
I arranged the file and added the relations between the classes according to the way we talked. 
As far as we talked after this the next steps are assigned as:
@bwqr : is assigned to draw the classes with their methods and fields in the diagram
@burakyuksel0 : is assigned to draw the relations the diagram

**Also**: as I mentioned in the meeting as well, we need to add some fields and variables to user classes in general. We should also talk about whether it will effect the use-case and sequence diagrams.

**Comment by barandenizkorkmaz** [comment]
According to the feedback No.3
3.The type of trading equipment should be specific for prediction success ratio (e.g., BIST100 prediction success ratio). 
I think the assistant meant The prediction success ratio should be specific for the type of the trading equipment.
Necessary arrangements should be done.

**Comment by irmakguzey** [comment]
Just wanted to give all of us a little heads up:
* And @bwqr and I have created the News class and rearranged the Events class according to the feedback#6 we had. 
* _The prediction success ratio should be specific for the type of the trading equipment._ -- This was assigned to @bwqr according to the Meeting #5 we had. With this done the class diagram will be pretty much done i guess.
